// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WindowsFormsApp2;

namespace WindowsFormsApp2.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20230820133952_SixthCreate")]
    partial class SixthCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WindowsFormsApp2.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationsId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Azamat",
                            IIN = "990101200020",
                            LastName = "Zhiyentay",
                            MiddleName = "Salimzhanuly",
                            OrganizationsId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Sultan",
                            IIN = "890101200021",
                            LastName = "Abdulla",
                            MiddleName = "Abdulla",
                            OrganizationsId = 2
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Anil",
                            IIN = "790101200030",
                            LastName = "Kumar",
                            MiddleName = "Anadan",
                            OrganizationsId = 2
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Aleksei",
                            IIN = "690101200001",
                            LastName = "Lexus",
                            MiddleName = "Olegovich",
                            OrganizationsId = 3
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Nurzhan",
                            IIN = "960306200020",
                            LastName = "Pernebayev",
                            MiddleName = "Abibullauly",
                            OrganizationsId = 3
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Dias",
                            IIN = "900501200020",
                            LastName = "Yertay",
                            MiddleName = "Yerasuly",
                            OrganizationsId = 4
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Adbi",
                            IIN = "000110200020",
                            LastName = "Ali",
                            MiddleName = "Aliyev",
                            OrganizationsId = 4
                        });
                });

            modelBuilder.Entity("WindowsFormsApp2.Organizations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ЖК Керемет, корп.6",
                            INN = "001122",
                            Name = "LTD IVC",
                            Note = "Fintech"
                        },
                        new
                        {
                            Id = 2,
                            Address = "пр.Аль-Фараби, 10",
                            INN = "654321",
                            Name = "JSC BCC",
                            Note = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул.Назарбаева, 20",
                            INN = "123456",
                            Name = "JSC Halyk Bank",
                            Note = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            Address = "ул. Желтоксан, 181",
                            INN = "003322",
                            Name = "JSC Ayt Otel",
                            Note = "Hotel"
                        });
                });

            modelBuilder.Entity("WindowsFormsApp2.Employee", b =>
                {
                    b.HasOne("WindowsFormsApp2.Organizations", null)
                        .WithMany("Employees")
                        .HasForeignKey("OrganizationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
